/**
 * GalaxyField — Presets.
 * Cada preset es un conjunto PARCIAL de props; lo no especificado usa el default.
 */

import type { GalaxyFieldProps } from './GalaxyField'

export type GalaxyFieldPreset = Partial<GalaxyFieldProps>

export const GalaxyFieldPresets: Record<string, GalaxyFieldPreset> = {
  /** Paleta SOTSI: núcleo dorado, disco periwinkle. Es el look del blog. */
  Default: {
    coreColor: '#fed457',
    edgeColor: '#d2ccfd',
    count: 32000,
    branches: 4,
    spin: 1,
    radius: 5,
    randomness: 0.22,
    randomnessPower: 3,
    size: 26,
    twinkle: 0.35,
    tilt: 0.7,
    zoom: 8.2,
  },
  'Milky Way': {
    coreColor: '#fff2d0',
    edgeColor: '#7fa6ff',
    count: 40000,
    branches: 5,
    spin: 1.2,
    radius: 6,
    randomness: 0.42,
    randomnessPower: 3.4,
    size: 16,
    twinkle: 0.45,
    tilt: 0.28,
    zoom: 7.5,
  },
  Nebula: {
    coreColor: '#ffb3f0',
    edgeColor: '#6d5cff',
    count: 30000,
    branches: 3,
    spin: 1.6,
    radius: 5.5,
    randomness: 0.9,
    randomnessPower: 2.2,
    size: 28,
    twinkle: 0.3,
    tilt: 0.55,
    zoom: 6,
  },
  Cyberpunk: {
    coreColor: '#00e5ff',
    edgeColor: '#f000ff',
    count: 28000,
    branches: 6,
    spin: -1.4,
    radius: 5,
    randomness: 0.55,
    randomnessPower: 2.6,
    size: 20,
    twinkle: 0.7,
    tilt: 0.35,
    zoom: 6.2,
  },
  Ember: {
    coreColor: '#fff0c2',
    edgeColor: '#e0472a',
    count: 26000,
    branches: 4,
    spin: 1.1,
    radius: 5.2,
    randomness: 0.6,
    randomnessPower: 2.8,
    size: 24,
    twinkle: 0.5,
    tilt: 0.4,
    zoom: 6.4,
  },
  Ice: {
    coreColor: '#ffffff',
    edgeColor: '#5ec8f5',
    count: 32000,
    branches: 5,
    spin: 0.8,
    radius: 5.6,
    randomness: 0.35,
    randomnessPower: 3.6,
    size: 15,
    twinkle: 0.55,
    tilt: 0.3,
    zoom: 7,
  },
  Aurora: {
    coreColor: '#d9ffe8',
    edgeColor: '#5b8cff',
    count: 30000,
    branches: 3,
    spin: 1.8,
    radius: 6,
    randomness: 0.7,
    randomnessPower: 2.4,
    size: 22,
    twinkle: 0.4,
    tilt: 0.5,
    zoom: 6.6,
  },
  Monochrome: {
    coreColor: '#ffffff',
    edgeColor: '#6b7280',
    count: 26000,
    branches: 4,
    spin: 1,
    radius: 5,
    randomness: 0.5,
    randomnessPower: 3,
    size: 18,
    twinkle: 0.25,
    tilt: 0.42,
    zoom: 6.5,
  },
  /** Vista casi de canto: la galaxia se ve como un disco lateral. */
  'Edge On': {
    coreColor: '#ffe0a8',
    edgeColor: '#9b8cff',
    count: 45000,
    branches: 5,
    spin: 1.3,
    radius: 6.5,
    randomness: 0.3,
    randomnessPower: 4,
    thickness: 0.12,
    size: 14,
    twinkle: 0.4,
    tilt: 0.04,
    zoom: 8,
  },
}

export const GalaxyFieldPresetNames = Object.keys(GalaxyFieldPresets)
